#
# This file is part of tempera. Copyright (C) 2018 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at https://choosealicense.com/licenses/mit.
#

[[constraint]]
  name = "github.com/franela/goblin"
  version = "0.0.1"

[prune]
  go-tests = true
  unused-packages = true
